
# OAuth client IDs and secrets (populated from environment variables)
# GOOGLE_CLIENT_ID
# GOOGLE_CLIENT_SECRET
# DROPBOX_CLIENT_ID
# DROPBOX_CLIENT_SECRET

# Supabase configs for authentication
# SUPABASE_URL
# SUPABASE_SERVICE_ROLE_KEY
